<div style='text-indent: 0 cm; background-color: white; color: black; padding-top: 20px; padding-bottom: 10px;'>

# <span style='display: flex; justify-content: center; color: #E54646'><b>COMPOSITE KEY CONSTRAINT</b></span>

<div align='justify'>
<blockquote style='background-color: white; color: black'>

<p>To know what a composite key is, we need to have the knowledge of what a primary key is. A primary key is a column that has a unique and not null value in an SQL table.</p>

<p>Now, a composite key is also a primary key, but the difference is that it is made by the combination of more than one column to identify the particular row in the table.</p>

### <span style='color: #BD6B09'><strong>Composite Key</strong></span>

<p>A composite key is made by the combination of two or more columns in a table that can be used to uniquely identify each row in the table. When the columns are combined, the uniqueness of a row is guaranteed, but when taken individually, it does not guarantee uniqueness. It can also be understood as a primary key made by the combination of two or more attributes to uniquely identify every row in a table.</p>

<p><strong>Note</strong></p>

<li style='text-indent: 1cm'>A composite key can also be made by the combination of more than one candidate key.</li>
<li style='text-indent: 1cm'>A composite key cannot be null.</li>

### <span style='color: #BD6B09'><strong>Example</strong></span>

<p><strong>Creating a database</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>CREATE DATABASE</span> School;
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong>Using database</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>USE School;</span> School;
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong>Creating table with a composite key</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>CREATE TABLE</span> student
(
  rollNumber <span style='color: #BD6B09'>INT</span>, 
  name <span style='color: #BD6B09'>VARCHAR</span>(30), 
  class <span style='color: #BD6B09'>VARCHAR</span>(30), 
  section <span style='color: #BD6B09'>VARCHAR</span>(1), 
  mobile <span style='color: #BD6B09'>VARCHAR</span>(10),
  <span style='color: #BD6B09'>PRIMARY KEY</span> (rollNumber, mobile)
);
</pre>
      </strong>
    </th>
  </tr>
</table>

<p>In this example, we have made the composite key as the combination of two columns i.e. rollNumber and mobile because all the rows of the table student can be uniquely identified by this composite key.</p>

<p><strong>Inserting records in the table</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>INSERT INTO</span> student (rollNumber, name, class, section, mobile)
<span style='color: #BD6B09'>VALUES</span> (1, "AMAN", "FOURTH", "B", "9988774455");

<span style='color: #BD6B09'>INSERT INTO</span> student (rollNumber, name, class, section, mobile)
<span style='color: #BD6B09'>VALUES</span> (2, "JOHN", "FIRST", "A", "9988112233");

<span style='color: #BD6B09'>INSERT INTO</span> student (rollNumber, name, class, section, mobile)
<span style='color: #BD6B09'>VALUES</span> (3, "TOM", "FOURTH", "B", "9988777755");

<span style='color: #BD6B09'>INSERT INTO</span> student (rollNumber, name, class, section, mobile)
<span style='color: #BD6B09'>VALUES</span> (4, "RICHARD", "SECOND", "C", "9955663322");
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong>Querying the records</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> * 
<span style='color: #BD6B09'>FROM</span> student;
</pre>
      </strong>
    </th>
  </tr>
</table>


<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210412195107/Screenshot157.png' style='border: solid black 5px'><br><small><i></i></small></div>