<div style='text-indent: 0 cm; background-color: white; color: black; padding-top: 20px; padding-bottom: 10px;'>

# <span style='display: flex; justify-content: center; color: #E54646'><b>CHECK CONSTRAINT</b></span>

<div align='justify'>
<blockquote style='background-color: white; color: black'>

<p>SQL Constraints Check Constraint is used to specify a predicate that every tuple must satisfy in a given relation. It limits the values that a column can hold in a relation.</p>

<li style='text-indent: 1cm'>The predicate in check constraint can hold a sub query.</li>
<li style='text-indent: 1cm'>Check constraint defined on an attribute restricts the range of values for that attribute.</li>
<li style='text-indent: 1cm'>If the value being added to an attribute of a tuple violates the check constraint, the check constraint evaluates to false and the corresponding update is aborted.</li>
<li style='text-indent: 1cm'>Check constraint is generally specified with the CREATE TABLE command in SQL.</li>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>CREATE TABLE</span> pets (
    ID INT <span style='color: #BD6B09'>NOT NULL</span>,
    Name VARCHAR(30) <span style='color: #BD6B09'>NOT NULL</span>,
    Breed VARCHAR(20) <span style='color: #BD6B09'>NOT NULL</span>,
    Age INT,
    GENDER VARCHAR(9),
    <span style='color: #BD6B09'>PRIMARY KEY</span>(ID),
    <span style='color: #BD6B09'>CHECK</span>(GENDER <span style='color: #BD6B09'>IN</span> ('Male', 'Female', 'Unknown'))
);
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong>Note</strong>: The check constraint in the above SQL command restricts the GENDER to belong to only the categories specified. If a new tuple is added or an existing tuple in the relation is updated with a GENDER that doesn’t belong to any of the three categories mentioned, then the corresponding database update is aborted.</p>

### <span style='color: #BD6B09'><strong>Query</strong></span>

<p>Constraint: Only students with age >= 17 are can enroll themselves in a university. <strong>Schema for student database in university</strong>.</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>CREATE TABLE</span> student (
    StudentID INT <span style='color: #BD6B09'>NOT NULL</span>,
    Name VARCHAR(30) <span style='color: #BD6B09'>NOT NULL</span>,
    Age INT <span style='color: #BD6B09'>NOT NULL</span>,
    GENDER VARCHAR(9),
    <span style='color: #BD6B09'>PRIMARY KEY</span>(StudentID),
    <span style='color: #BD6B09'>CHECK</span>(Age <span style='color: #BD6B09'>>=</span> 17)
);
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong>Student relation</strong></p>

<table align="center" border="1">
    <tr align="center" style='background-color: #F0F0F0; color: black'>
        <th>StudentID</th>
        <th>Name</th>
        <th>Age</th>
        <th>Gender</th>
    </tr>
    <tr align="center">
        <td>1001</td>
        <td>Ron</td>
        <td>18</td>
        <td>Male</td>
    </tr>
    <tr align="center">
        <td>1002</td>
        <td>Sam</td>
        <td>17</td>
        <td>Male</td>
    </tr>
    <tr align="center">
        <td>1003</td>
        <td>Georgia</td>
        <td>17</td>
        <td>Female</td>
    </tr>
    <tr align="center">
        <td>1004</td>
        <td>Erik</td>
        <td>19</td>
        <td>Unknown</td>
    </tr>
    <tr align="center">
        <td>1005</td>
        <td>Christine</td>
        <td>17</td>
        <td>Female</td>
    </tr>
</table>

<p><strong>Explanation</strong>: In the above relation, the age of all students is greater than equal to 17 years, according to the constraint mentioned in the check statement in the schema of the relation. If, however following SQL statement is executed:</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>INSERT INTO</span> student (StudentID, Name, Age, GENDER)
<span style='color: #BD6B09'>VALUES</span> (1006, 'Emma', 16, 'Female');
</pre>
      </strong>
    </th>
  </tr>
</table>

<p>There won’t be any database update and as the age < 17 years. Different options to use <strong>Check constraint</strong>: </p>

<p><strong><u>With alter</u></strong>: Check constraint can also be added to an already created relation using the syntax:</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>ALTER TABLE</span> TABLE_NAME 
<span style='color: #BD6B09'>MODIFY</span> COLUMN_NAME 
<span style='color: #BD6B09'>CHECK</span> (Predicate);
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong><u>Giving variable name to check constraint</u></strong>:Check constraints can be given a variable name using the syntax:</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>ALTER TABLE</span> TABLE_NAME 
<span style='color: #BD6B09'>ADD CONSTRAINT</span> CHECK_CONST 
<span style='color: #BD6B09'>CHECK</span> (Predicate);
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong><u>Remove check constraint</u></strong>: Check constraint can be removed from the relation in the database from SQL server using the syntax:</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>ALTER TABLE</span> TABLE_NAME 
<span style='color: #BD6B09'>DROP CONSTRAINT</span> CHECK_CONSTRAINT_NAME;
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong><u>Drop check constraint</u></strong>: Check constraint can be dropped from the relation in the database in MySQL using the syntax:</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>ALTER TABLE</span> TABLE_NAME 
<span style='color: #BD6B09'>DROP CHECK</span> CHECK_CONSTRAINT_NAME;
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong>View existing constraints on a particular table</strong></p>

<p>If you want to check if a constraint or any constraint exists within the table in mysql then you can use the following command. This command will show a tabular output of all the constraint-related data for the table name you’ve passed in the statement, in our case we’ll use the employee table.</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> * <span style='color: #BD6B09'>FROM</span> information_schema.table_constraints 
<span style='color: #BD6B09'>WHERE</span> table_schema = schema() <span style='color: #BD6B09'>AND</span> table_name = 'employee';
</pre>
      </strong>
    </th>
  </tr>
</table>