<div style='text-indent: 0 cm; background-color: white; color: black; padding-top: 20px; padding-bottom: 10px;'>

# <span style='display: flex; justify-content: center; color: #E54646'><b>DEFAULT CONSTRAINT</b></span>

<div align='justify'>
<blockquote style='background-color: white; color: black'>

<p>The <strong>DEFAULT Constraint</strong> is used to fill a column with a default and fixed value. The value will be added to all new records when no other value is provided.</p>

### <span style='color: #BD6B09'><strong>Syntax</strong></span>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>CREATE TABLE</span> tablename (
    Columnname datatype <span style='color: #BD6B09'>DEFAULT</span> 'defaultvalue'
);
</pre>
      </strong>
    </th>
  </tr>
</table>

### <span style='color: #BD6B09'><strong>Using DEFAULT on CREATE TABLE</strong></span>

<p>To set a DEFAULT value for the “Location” column when the “Geeks” table is created.</p>

<p><strong>Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>CREATE TABLE</span> Geeks (
    ID int <span style='color: #BD6B09'>NOT NULL</span>,
    Name varchar(255),
    Age int,
    Location varchar(255) <span style='color: #BD6B09'>DEFAULT</span> 'Noida'
);

<span style='color: #BD6B09'>INSERT INTO</span> Geeks <span style='color: #BD6B09'>VALUES</span> (4, 'Mira', 23, 'Delhi');
<span style='color: #BD6B09'>INSERT INTO</span> Geeks <span style='color: #BD6B09'>VALUES</span> (5, 'Hema', 27, <span style='color: #BD6B09'>DEFAULT</span>);
<span style='color: #BD6B09'>INSERT INTO</span> Geeks <span style='color: #BD6B09'>VALUES</span> (6, 'Neha', 25, 'Delhi');
<span style='color: #BD6B09'>INSERT INTO</span> Geeks <span style='color: #BD6B09'>VALUES</span> (7, 'Khushi', 26, <span style='color: #BD6B09'>DEFAULT</span>);

<span style='color: #BD6B09'>SELECT</span> * <span style='color: #BD6B09'>FROM</span> Geeks;
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20230331172956/Screenshot-from-2023-03-31-17-29-44.png' style='border: solid black 5px'><br><small><i></i></small></div>

### <span style='color: #BD6B09'><strong>DROP a DEFAULT Constraint</strong></span>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>ALTER TABLE</span> tablename
<span style='color: #BD6B09'>ALTER COLUMN</span> columnname
<span style='color: #BD6B09'>DROP DEFAULT</span>;
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong>Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>ALTER TABLE</span> Geeks
<span style='color: #BD6B09'>ALTER COLUMN</span> Location
<span style='color: #BD6B09'>DROP DEFAULT</span>;
</pre>
      </strong>
    </th>
  </tr>
</table>

<p>Let us add 2 new rows in the Geeks table:</p>

<p><strong>Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>INSERT INTO</span> Geeks <span style='color: #BD6B09'>VALUES</span> (8, 'Komal', 24, 'Delhi');
<span style='color: #BD6B09'>INSERT INTO</span> Geeks <span style='color: #BD6B09'>VALUES</span> (9, 'Payal', 26, <span style='color: #BD6B09'>NULL</span>);
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong>Note</strong> – Dropping the default constraint will not affect the current data in the table, it will only apply to new rows.</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <th style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> * <span style='color: #BD6B09'>FROM</span> Geeks;
</pre>
      </strong>
    </th>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20230403154731/Screenshot_27.png' style='border: solid black 5px'><br><small><i></i></small></div>