<div style='text-indent: 0 cm; background-color: white; color: black; padding-top: 20px; padding-bottom: 10px;'>

# <span style='display: flex; justify-content: center; color: #E54646'><b>STRING FUNCTIONS</b></span>

<div align='justify'>
<blockquote style='background-color: white; color: black'>

<p><strong>String functions</strong> are used to perform an operation on input string and return an output string. Following are the string functions defined in SQL:</p>

<p><strong style='color: #BD6B09'>ASCII()</strong> This function is used to find the ASCII value of a character.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>ascii</span>(<span style='color: #008000'>'t'</span>);</pre></strong></td></tr>
</table>

<p><strong>Output</strong>: 116</p>

<p><strong style='color: #BD6B09'>CHAR_LENGTH()</strong>: Doesn’t work for SQL Server. Use LEN() for SQL Server. This function is used to find the length of a word.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>char_length</span>(<span style='color: #008000'>'Hello!'</span>);</pre></strong></td></tr>
</table>

<p><strong>Output</strong>: 6</p>

<p><strong style='color: #BD6B09'>CHARACTER_LENGTH()</strong>: Doesn’t work for SQL Server. Use LEN() for SQL Server. This function is used to find the length of a line.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>CHARACTER_LENGTH</span>(<span style='color: #008000'>'geeks for geeks'</span>);</pre></strong></td></tr>
</table>

<p><strong>Output</strong>: 15</p>

<p><strong style='color: #BD6B09'>CONCAT()</strong>: This function is used to add two words or strings.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #008000'>'Geeks'</span> <span style='color: #BD6B09'>||</span> <span style='color: #008000'>' '</span> <span style='color: #BD6B09'>||</span> <span style='color: #008000'>'forGeeks'</span> <span style='color: #BD6B09'>FROM</span> <span style='color: #008000'>dual</span>;</pre></strong></td></tr>
</table>

<p><strong>Output</strong>: ‘Geeks forGeeks’</p>

<p><strong style='color: #BD6B09'>CONCAT_WS()</strong>: This function is used to add two words or strings with a symbol as concatenating symbol.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>CONCAT_WS</span>(<span style='color: #008000'>'_'</span>, <span style='color: #008000'>'geeks'</span>, <span style='color: #008000'>'for'</span>, <span style='color: #008000'>'geeks'</span>);</pre></strong></td></tr>
</table>

<p><strong>Output</strong>: geeks_for_geeks</p>

<p><strong style='color: #BD6B09'>FIND_IN_SET()</strong>: This function is used to find a symbol from a set of symbols.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>FIND_IN_SET</span>(<span style='color: #008000'>'b'</span>, <span style='color: #008000'>'a, b, c, d, e, f'</span>);</pre></strong></td></tr>
</table>

<p><strong>Output</strong>: 2</p>

<p><strong style='color: #BD6B09'>FORMAT()</strong>: This function is used to display a number in the given format.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>FORMAT</span>(<span style='color: #008000'>"0.981"</span>, <span style='color: #008000'>"Percent"</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: ‘98.10%’</p>

<p><strong style='color: #BD6B09'>INSERT()</strong>: This function is used to insert the data into a database.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>INSERT INTO</span> <span style='color: #008000'>database</span> 
(<span style='color: #008000'>geek_id</span>, <span style='color: #008000'>geek_name</span>) 
<span style='color: #BD6B09'>VALUES</span> 
(<span style='color: #008000'>5000</span>, <span style='color: #008000'>'abc'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: successfully updated</p>

<p><strong style='color: #BD6B09'>INSTR()</strong>: This function is used to find the occurrence of an alphabet.</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>INSTR</span>(<span style='color: #008000'>'geeks for geeks'</span>, <span style='color: #008000'>'e'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: 2 (the first occurrence of ‘e’)</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>INSTR</span>(<span style='color: #008000'>'geeks for geeks'</span>, <span style='color: #008000'>'e'</span>, <span style='color: #008000'>1</span>, <span style='color: #008000'>2</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: 3 (the second occurrence of ‘e’)</p>

<p><strong style='color: #BD6B09'>LCASE()</strong>: This function is used to convert the given string into lower case.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>LCASE</span>(<span style='color: #008000'>"GeeksFor Geeks To Learn"</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: geeksforgeeks to learn</p>

<p><strong style='color: #BD6B09'>LEFT()</strong>: This function is used to SELECT a sub string from the left of given size or characters.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>LEFT</span>(<span style='color: #008000'>'geeksforgeeks.org'</span>, <span style='color: #008000'>5</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: geeks</p>

<p><strong style='color: #BD6B09'>LENGTH()</strong>: This function is used to find the length of a word.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>LENGTH</span>(<span style='color: #008000'>'GeeksForGeeks'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: 13</p>

<p><strong style='color: #BD6B09'>LOCATE()</strong>: This function is used to find the nth position of the given word in a string.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>LOCATE</span>(<span style='color: #008000'>'for'</span>, <span style='color: #008000'>'geeksforgeeks'</span>, <span style='color: #008000'>1</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: 6</p>

<p><strong style='color: #BD6B09'>LOWER()</strong>: This function is used to convert the upper case string into lower case.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>LOWER</span>(<span style='color: #008000'>'GEEKSFORGEEKS.ORG'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: geeksforgeeks.org</p>

<p><strong style='color: #BD6B09'>LPAD()</strong>: This function is used to make the given string of the given size by adding the given symbol.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>LPAD</span>(<span style='color: #008000'>'geeks'</span>, <span style='color: #008000'>8</span>, <span style='color: #008000'>'0'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: 000geeks</p>

<p><strong style='color: #BD6B09'>LTRIM()</strong>: This function is used to cut the given sub string from the original string.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>LTRIM</span>(<span style='color: #008000'>'123123geeks'</span>, <span style='color: #008000'>'123'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: geeks</p>

<p><strong style='color: #BD6B09'>MID()</strong>: This function is to find a word from the given position and of the given size.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>MID</span>(<span style='color: #008000'>"geeksforgeeks"</span>, <span style='color: #008000'>6</span>, <span style='color: #008000'>2</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: for</p>

<p><strong style='color: #BD6B09'>POSITION()</strong>: This function is used to find position of the first occurrence of the given alphabet.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>POSITION</span>(<span style='color: #008000>'e'</span> <span style='color: #BD6B09>IN</span> <span style='color: #008000>'geeksforgeeks'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: 2</p>

<p><strong style='color: #BD6B09'>REPEAT()</strong>: This function is used to write the given string again and again till the number of times mentioned.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>REPEAT</span>(<span style='color: #008000>'geeks'</span>, <span style='color: #008000'>2</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: geeksgeeks</p>

<p><strong style='color: #BD6B09'>REPLACE()</strong>: This function is used to cut the given string by removing the given sub string.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>REPLACE</span>(<span style='color: #008000>'123geeks123'</span>, <span style='color: #008000>'123'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: geeks</p>

<p><strong style='color: #BD6B09'>REVERSE()</strong>: This function is used to reverse a string.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>REVERSE</span>(<span style='color: #008000>'geeksforgeeks.org'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: ‘gro.skeegrofskeeg’</p>

<p><strong style='color: #BD6B09'>RIGHT()</strong>: This function is used to SELECT a sub string from the right end of the given size.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>RIGHT</span>(<span style='color: #008000>'geeksforgeeks.org'</span>, <span style='color: #008000'>4</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: ‘.org’</p>

<p><strong style='color: #BD6B09'>RPAD()</strong>: This function is used to make the given string as long as the given size by adding the given symbol on the right.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>RPAD</span>(<span style='color: #008000>'geeks'</span>, <span style='color: #008000'>8</span>, <span style='color: #008000>'0'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: ‘geeks000’</p>

<p><strong style='color: #BD6B09'>RTRIM()</strong>: This function is used to cut the given sub string from the original string.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>RTRIM</span>(<span style='color: #008000>'geeksxyxzyyy'</span>, <span style='color: #008000>'xyz'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: ‘geeks’</p>

<p><strong style='color: #BD6B09'>SPACE()</strong>: This function is used to write the given number of spaces.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>SPACE</span>(<span style='color: #008000'>7</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: ‘       ‘</p>

<p><strong style='color: #BD6B09'>STRCMP()</strong>: This function is used to compare 2 strings.</p>

<li style='text-indent: 1cm'>If string1 and string2 are the same, the STRCMP function will return 0.</li>
<li style='text-indent: 1cm'>If string1 is smaller than string2, the STRCMP function will return -1.</li>
<li style='text-indent: 1cm'>If string1 is larger than string2, the STRCMP function will return 1.</li>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>STRCMP</span>(<span style='color: #008000>'google.com'</span>, <span style='color: #008000>'geeksforgeeks.com'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: -1</p>

<p><strong style='color: #BD6B09'>SUBSTR()</strong>: This function is used to find a sub string from the a string from the given position.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>SUBSTR</span>(<span style='color: #008000>'geeksforgeeks'</span>, <span style='color: #008000'>1</span>, <span style='color: #008000'>5</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: ‘geeks’</p>

<p><strong style='color: #BD6B09'>SUBSTRING()</strong>: This function is used to find an alphabet from the mentioned size and the given string.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>SUBSTRING</span>(<span style='color: #008000>'GeeksForGeeks.org'</span>, <span style='color: #008000'>9</span>, <span style='color: #008000'>1</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: ‘G’</p>

<p><strong style='color: #BD6B09'>SUBSTRING_INDEX()</strong>: This function is used to find a sub string before the given symbol.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>SUBSTRING_INDEX</span>(<span style='color: #008000>'www.geeksforgeeks.org'</span>, <span style='color: #008000>'-'</span>, <span style='color: #008000'>1</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: ‘www’</p>

<p><strong style='color: #BD6B09'>TRIM()</strong>: This function is used to cut the given symbol from the string.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>TRIM</span>(<span style='color: #BD6B09'>LEADING</span> <span style='color: #008000>'0'</span> <span style='color: #BD6B09'>FROM</span> <span style='color: #008000>'000123'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: 123</p>

<p><strong style='color: #BD6B09'>UCASE()</strong>: This function is used to make the string in upper case..</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <pre>
<span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>UCASE</span>(<span style='color: #008000>'GeeksForGeeks'</span>);</pre>
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong>: GEEKSFORGEEKS</p>