<div style='text-indent: 0 cm; background-color: white; color: black; padding-top: 20px; padding-bottom: 10px;'>

# <span style='display: flex; justify-content: center; color: #E54646'><b>WORKING WITH JSON IN SQL</b></span>

<div align='justify'>
<blockquote style='background-color: white; color: black'>

<p>JSON stands for Javascript Object Notation. It is mainly used in storing and transporting data. Mostly all NoSQL databases like MongoDB, CouchDB, etc., use JSON format data. Whenever your data from one server has to be transferred to a web page, JSON format is the preferred format as front-end applications like Android, iOS, React or Angular, etc., can parse the JSON contents and display them according to convenience. Even in SQL, we can send JSON data and can store them easily in rows. Let us see one by one.</p>

### <span style='color: #BD6B09'><strong>Database creation</strong></span>

<p>Command to create the database.  Here GEEKSFORGEEKS is the db name.</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>CREATE DATABASE</span> GEEKSFORGEEKS;
      </strong>
    </td>
  </tr>
</table>

<p>To make the database active use the below command:</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>USE</span> GEEKSFORGEEKS;
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210528114711/DATABASECREATION.png' style='border: solid black 5px'><br><small><i></i></small></div>

### <span style='color: #BD6B09'><strong>Creating Tables with Data</strong></span>

<p>Now let us create a table named “<strong>Authors</strong>” and let us insert some data to it as shown below:</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>CREATE TABLE</span> Authors (
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>ID</span> INT IDENTITY <span style='color: #BD6B09'>NOT NULL</span> <span style='color: #BD6B09'>PRIMARY KEY</span>,
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>AuthorName</span> NVARCHAR(MAX),
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>Age</span> INT,
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>Skillsets</span> NVARCHAR(MAX),
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>NumberOfPosts</span> INT
        <br>);
        <br><span style='color: #BD6B09'>INSERT INTO</span> Authors (AuthorName, Age, Skillsets, NumberOfPosts) 
        <br><span style='color: #BD6B09'>VALUES</span> ('Geek', 25, 'Java, Python, .Net', 5);
        <br><span style='color: #BD6B09'>GO</span>
        <br><span style='color: #BD6B09'>INSERT INTO</span> Authors (AuthorName, Age, Skillsets, NumberOfPosts) 
        <br><span style='color: #BD6B09'>VALUES</span> ('Geek2', 22, 'Android, Python, .Net', 15);
        <br><span style='color: #BD6B09'>GO</span>
        <br><span style='color: #BD6B09'>INSERT INTO</span> Authors (AuthorName, Age, Skillsets, NumberOfPosts) 
        <br><span style='color: #BD6B09'>VALUES</span> ('Geek3', 23, 'IOS, GO, R', 10);
        <br><span style='color: #BD6B09'>GO</span>
        <br><span style='color: #BD6B09'>INSERT INTO</span> Authors (AuthorName, Age, Skillsets, NumberOfPosts) 
        <br><span style='color: #BD6B09'>VALUES</span> ('Geek4', 24, 'Java, Python, GO', 5);
        <br><span style='color: #BD6B09'>GO</span>
      </strong>
    </td>
  </tr>
</table>

<p>JSON is a beautiful option for bridging NoSQL and relational worlds. Hence, in case if you have the data got exported from MongoDB and need to import them in SQL Server, we can follow below approaches.</p>

<p>JSON documents can be stored as-is in NVARCHAR columns either in LOB storage format or Relational storage format. Raw JSON documents have to be parsed, and they may contain Non-English text.  By using nvarchar(max) data type, we can store JSON documents with a max capacity of 2 GB in size. If the JSON data is not huge, we can go for  NVARCHAR(4000), or else we can go for NVARCHAR(max) for performance reasons.</p>

### <span style='color: #BD6B09'><strong>Cross feature compatibility</strong></span>

<p>The main reason for keeping the JSON document in NVARCHAR  format is for Cross feature compatibility. NVARCHAR  works with X feature i.e. all the SQL server components such as Hekaton(OLTP), temporal, or column store tables, etc. As JSON behavior is also in that way, it is represented as NVARCHAR datatype.</p>

### <span style='color: #BD6B09'><strong>Migration</strong></span>

<p>Before SQL Server 2016, JSON was stored in the database as text. Hence, there was a need to change the database schema and migration occurred as JSON type in NVarchar format.</p>

### <span style='color: #BD6B09'><strong>Client-side support</strong></span>

<p>JSON is just treated as an Object in JavaScript and hence called as Javascript Object Notation. There is no specific  standardized JSON object type on client-side available similar to XmlDom object.</p>

<p>Let us see the important functionalities available in SQL Server which can be used with JSON data.</p>

### <span style='color: #BD6B09'><strong>Example JSON Data</strong></span>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>JSON</span>:
        <br>
        <span style='color: #BD6B09'>{</span>
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>"Information"</span>:
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>"SchoolDetails"</span>:
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>"Name"</span>: <span style='color: #008000'>"VidhyaMandhir"</span>
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>"Name"</span>: <span style='color: #008000'>"Chettinad"</span>
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>"Name"</span>: <span style='color: #008000'>"PSSenior"</span>
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
        <span style='color: #BD6B09'>}</span>
      </strong>
    </td>
  </tr>
</table>

### <span style='color: #BD6B09'><strong>1. ISJSON (JSON string)</strong></span>

<p>This function is used to check whether the <strong>given input json string is in JSON format or not</strong>. If it is in JSON format, it returns 1 as output or else 0. i.e. it returns either 1 or 0 in INT format.</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>ISJSON</span>(@JSONData) 
        <span style='color: #BD6B09'>AS</span> VALIDJSON;
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210603153336/validjson.png' style='border: solid black 5px'><br><small><i></i></small></div>

### <span style='color: #BD6B09'><strong>2. JSON_VALUE (JSON string, path)</strong></span>

<p>The output will be a scalar value from the given JSON string. Parsing of JSON string is done and there are some specific formats are there for providing the path. For example:</p>

<li style='text-indent: 1cm'>‘$’ – reference entire JSON object</li>
<li style='text-indent: 1cm'>‘$.Example1’ – reference Example1in JSON object</li>
<li style='text-indent: 1cm'>‘$[4]’ – reference 4th element in JSON array</li>
<li style='text-indent: 1cm'>‘$.Example1.Example2[2].Example3’ – reference nested property in JSON object</li>

<p><strong>Example</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>JSON_VALUE</span>(@JSONData, <span style='color: #008000>'$.Information.SchoolDetails[0].Name'</span>) 
        <span style='color: #BD6B09'>AS</span> SchoolName;
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210603154653/schoolname.png' style='border: solid black 5px'><br><small><i></i></small></div>

### <span style='color: #BD6B09'><strong>3. JSON_QUERY(JSON string, path)</strong></span>

<p>Used to extract an array of data or objects from the JSON string.</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>JSON_QUERY</span>(@JSONData, <span style='color: #008000>'$.Information.SchoolDetails'</span>) 
        <span style='color: #BD6B09'>AS</span> LISTOFSCHOOLS;
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210603155544/LISTOFSCHOOLS.png' style='border: solid black 5px'><br><small><i>LIST OF SCHOOLS BY MEANS OF JSON_QUERY</i></small></div>

### <span style='color: #BD6B09'><strong>4. JSON_MODIFY</strong></span>

<p>There is an option called “JSON_MODIFY” in  (Transact-SQL) function is available to update the value of a property in a JSON string and return the updated JSON string. Whenever there is a requirement to change JSON text, we can do that:</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SET</span> @JSONData = <span style='color: #BD6B09'>JSON_MODIFY</span>(@JSONData, <span style='color: #008000>'$.Information.SchoolDetails[2].Name'</span>, <span style='color: #008000>'Adhyapana'</span>);
        <br>
        <span style='color: #BD6B09'>SELECT</span> modifiedJson = @JSONData;
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210603160818/jsonmodify.png' style='border: solid black 5px'><br><small><i></i></small></div>

### <span style='color: #BD6B09'><strong>5. FOR JSON</strong></span>

<p>This function is used for Exporting SQL Server data as JSON format. This is a useful function to export SQL  data into JSON format.  There are two options available with FOR JSON.</p>

<li style='text-indent: 1cm'><strong>AUTO</strong>: As it is nested JSON sub-array is created based on the table hierarchy.</li>

<li style='text-indent: 1cm'><strong>PATH</strong>:  By using this we can define the structure of JSON in a customized way.</li>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210603170902/authors.png' style='border: solid black 5px'><br><small><i>Authors table output</i></small></div>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> * 
        <span style='color: #BD6B09'>FROM</span> Authors 
        <span style='color: #BD6B09'>FOR JSON AUTO</span>;
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210603171324/authorsjson.png' style='border: solid black 5px'><br><small><i></i></small></div>

<br>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> * 
        <span style='color: #BD6B09'>FROM</span> Authors 
        <span style='color: #BD6B09'>FOR JSON AUTO</span>, 
        <span style='color: #BD6B09'>ROOT</span> (<span style='color: #008000>'AuthorInfo'</span>);
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210603171622/authorinfo.png' style='border: solid black 5px'><br><small><i></i></small></div>

### <span style='color: #BD6B09'><strong>6. OPENJSON</strong></span>

<p>This function is used for importing JSON as String data. We can import JSON as a text file by using OPENROWSET function and in that the BULK option should be enabled. It returns a single string field with BulkColumn as its column name.</p>

<p><strong>Example</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>DECLARE</span> @JSON <span style='color: #BD6B09'>VARCHAR(MAX)</span>
        <br>
        <span style='color: #BD6B09'>--Syntax to get json data using OPENROWSET</span>
        <br>
        <span style='color: #BD6B09'>SELECT</span> @JSON = BulkColumn 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>FROM</span> OPENROWSET  
        <br>&nbsp;&nbsp;&nbsp;&nbsp;(<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>BULK</span> '<span style='color: #008000'><pathname\jsonfilename with .json extension></span>', <span style='color: #BD6B09'>SINGLE_CLOB</span>)  
        <br>&nbsp;&nbsp;&nbsp;&nbsp;AS j
        <br>
        <span style='color: #BD6B09'>--To check json valid or not, we are using this ISJSON</span>
        <br>
        <span style='color: #BD6B09'>SELECT</span> ISJSON(@JSON)
        <br>
        <span style='color: #BD6B09'>--If ISJSON is true, then display the json data</span>
        <br>
        <span style='color: #BD6B09'>IF</span> (ISJSON(@JSON) = 1)
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>SELECT</span> @JSON <span style='color: #BD6B09'>AS</span> 'JSON Text'
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210531144546/isjson.png' style='border: solid black 5px'><br><small><i></i></small></div>

<p><strong>Note</strong>: Even large data also can be placed. As a sample, we showed only a single row.</p>

<p>SINGLE_BLOB, which reads a file as varbinary(max). SINGLE_NCLOB, which reads a file as nvarchar(max)  — If the contents are in Non-English text like Japanese or Chinese etc., data, we need to go in this pattern.  We used SINGLE_CLOB, which reads a file as varchar(max).</p>

<p>It will generate a relational table with its contents from the JSON string. Each row is created which can be got by iterating through JSON object elements, OPENJSON  can be used to parse the JSON as a text. Let us have a JSON placed in an external file and its contents are:</p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210603161719/data1.png' style='border: solid black 5px'><br><small><i></i></small></div>

<br>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> * 
        <br><span style='color: #BD6B09'>FROM</span> <span style='color: #BD6B09'>OPENJSON</span> (@JSON)
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210531145154/openjson.png' style='border: solid black 5px'><br><small><i></i></small></div>

<br>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> @JSON = BulkColumn
        <br>
        <span style='color: #BD6B09'>FROM</span> OPENROWSET 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;(<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>BULK</span> '<span style='color: #008000'><location of json file></span>', <span style='color: #BD6B09'>SINGLE_CLOB</span>) 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;AS j
        <br>
        <span style='color: #BD6B09'>--If the retrieved JSON is a valid one</span>
        <br>
        <span style='color: #BD6B09'>IF</span> (ISJSON(@JSON) = 1)
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>SELECT</span> * 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>FROM</span> <span style='color: #BD6B09'>OPENJSON</span> (@JSON)
      </strong>
    </td>
  </tr>
</table>

<p>We can see that for “Strings” key like “authorname” and “skills” got type as 1 and “int” key like “id” and “age” got type as 2. Similarly, for boolean, the type is 3. For arrays, it is 4 and for object, it is 5. OPENJSON  parses only the root level of the JSON.</p>

<p><strong>In case if the JSON is nested, we need to use Path variables</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> * 
        <br><span style='color: #BD6B09'>FROM</span> <span style='color: #BD6B09'>OPENJSON</span> (@JSON, <span style='color: #008000>'$.skills'</span>)
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210531151340/nesteddataaccessing.png' style='border: solid black 5px'><br><small><i></i></small></div>

<p>We can even make the skillsets as columns of data as</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> * 
        <br><span style='color: #BD6B09'>FROM</span> <span style='color: #BD6B09'>OPENJSON</span> (@JSON, <span style='color: #008000>'$.skills'</span>)  
        <br><span style='color: #BD6B09'>WITH</span> (
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>skill1</span> <span style='color: #BD6B09'>VARCHAR</span>(<span style='color: #008000'>25</span>), 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>skill2</span> <span style='color: #BD6B09'>VARCHAR</span>(<span style='color: #008000'>25</span>), 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>skill3</span> <span style='color: #BD6B09'>VARCHAR</span>(<span style='color: #008000'>25</span>)
        <br>)
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210531152218/asarowformat.png' style='border: solid black 5px'><br><small><i></i></small></div>

<p><strong>Saving the rowset into Table</strong>: Here the number of columns should match the count that is present inside with:</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #008000'>&lt;col1&gt;</span>, <span style='color: #008000'>&lt;col2&gt;</span>, .... 
        <br><span style='color: #BD6B09'>INTO</span> <span style='color: #008000'>&lt;tablename&gt;</span> 
        <br><span style='color: #BD6B09'>FROM</span> <span style='color: #BD6B09'>OPENJSON</span> (@JSON, <span style='color: #008000>'$.skills'</span>)  
        <br><span style='color: #BD6B09'>WITH</span> (
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>skill1</span> <span style='color: #BD6B09'>VARCHAR</span>(<span style='color: #008000'>25</span>), 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>skill2</span> <span style='color: #BD6B09'>VARCHAR</span>(<span style='color: #008000'>25</span>), 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;<span style='color: #BD6B09'>skill3</span> <span style='color: #BD6B09'>VARCHAR</span>(<span style='color: #008000'>25</span>)
        <br>)
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210531153055/insertingintotable.png' style='border: solid black 5px'><br><small><i></i></small></div>

<p><strong>Changing JSON values</strong></p>

<p>There is an option called “JSON_MODIFY” in  (Transact-SQL) function is available to update the value of a property in a JSON string and return the updated JSON string. Whenever there is a requirement to change JSON text, we can do that</p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>DECLARE</span> @json <span style='color: #BD6B09'>NVARCHAR</span>(<span style='color: #008000'>MAX</span>);
        <br>
        <span style='color: #BD6B09'>SET</span> @json = <span style='color: #008000'>"{'Information': {'SchoolDetails': [{'Name': 'VidhyaMandhir'}, {'Name': 'Chettinad'}, {'Name':'PSSenior'}]}}"</span>;
        <br>
        <span style='color: #BD6B09'>SET</span> @json = <span style='color: #BD6B09'>JSON_MODIFY</span>(@json, <span style='color: #008000>'$.Information.SchoolDetails[2].Name'</span>, <span style='color: #008000>'Adhyapana'</span>);
        <br>
        <span style='color: #BD6B09'>SELECT</span> modifiedJson = @json;
      </strong>
    </td>
  </tr>
</table>

<br>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20210531133831/jsonmodify.png' style='border: solid black 5px'><br><small><i></i></small></div>

### <span style='color: #BD6B09'><strong>Conclusion</strong></span>

<p>JSON data is very much necessary nowadays and it is much required for storing and transportation of data across many servers and all software are using this for many useful purposes. All REST API calls provide JSON as output medium and in SQL Server , we have see how to use them.</p>