<div style='text-indent: 0 cm; background-color: white; color: black; padding-top: 20px; padding-bottom: 10px;'>

# <span style='display: flex; justify-content: center; color: #E54646'><b>Statistical Functions</b></span>

<div align='justify'>
<blockquote style='background-color: white; color: black'>

<p>SQL statistical functions are essential tools for extracting meaningful insights from databases. These functions, such as <strong>AVG()</strong>, <strong>SUM()</strong>, <strong>COUNT()</strong>, <strong>MIN()</strong>, <strong>MAX()</strong>, <strong>STDDEV()</strong>, and <strong>VAR()</strong>, enable users to perform statistical calculations on numeric data. Whether determining averages, sums, counts, or measures of variability, these functions empower efficient data analysis within the SQL environment.</p>

## <span style='color: #BD6B09'><strong>What is Statistics?</strong></span>

<p>So, <Strong>Statistics</strong> is a branch of mathematics that deals with data collection, analysis, interpretation, presentation, and organization. It involves the use of mathematical techniques to extract meaningful information from data. Statistics is widely used in various fields such as business, economics, social science, medicine, and engineering.</p>

## <span style='color: #BD6B09'><strong>Where do We Use Stats?</strong></span>

<p>let’s define Statistical Function, A Statistical function is a mathematical function that helps us to process and analyze data to provide meaningful information about the dataset. For example mean, sum, min, max, standard deviation, etc.</p>

## <span style='color: #BD6B09'><strong>Statistical Functions in SQL</strong></span>

<p>Here are Some Common Statistical Functions in SQL:</p>

<table align='center'>
    <tr align='center' style='background-color: #F0F0F0'><strong>
        <th>Function</th>
        <th>Output</th>
    </strong></tr>
    <tr>
        <td align='center'><strong>AVG()</strong></td>
        <td>Calculates the average value of a numeric column.</td>
    </tr>
    <tr>
        <td align='center'><strong>SUM()</strong></td>
        <td>Calculates the sum of values in a numeric column.</td>
    </tr>
    <tr>
        <td align='center'><strong>COUNT()</strong></td>
        <td>Counts the number of rows in a result set or the number of non-null values in a column.</td>
    </tr>
    <tr>
        <td align='center'><strong>MIN()</strong></td>
        <td>Returns the minimum value in a column.</td>
    </tr>
    <tr>
        <td align='center'><strong>MAX()</strong></td>
        <td>Returns the maximum value in a column.</td>
    </tr>
    <tr>
        <td align='center'><strong>VAR() / VARIANCE()</strong></td>
        <td>Calculates the population variance of a numeric column.</td>
    </tr>
    <tr>
        <td align='center'><strong>CORR()</strong></td>
        <td>Calculates the correlation coefficient between two numeric columns.</td>
    </tr>
    <tr>
        <td align='center'><strong>COVAR_POP()</strong></td>
        <td>Calculates the population covariance between two numeric columns.</td>
    </tr>
    <tr>
        <td align='center'><strong>PERCENTILE_CONT()</strong></td>
        <td>Calculates a specified percentile value for a numeric column.</td>
    </tr>
</table>

## <span style='color: #BD6B09'><strong>Statistical Functions With Exmaple</strong></span>

<p>We have four tables in our database: ‘studentDetails,’ ’employees,’ ‘sales_data,’ and ‘financial_data.’ (The pictures are displayed below.)</p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20231224234513/StudentDetails.png' style='border: solid black 5px'><br><small><i>Table : StudentDetails</i></small></div>

<p><strong>employees Table</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20240102143041/Employeetable.png' style='border: solid black 5px'><br><small><i>Table:Employees</i></small></div>

<p><strong>sales_data</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20240102143126/Table_sale_data.png' style='border: solid black 5px'><br><small><i>Table:Sales_data</i></small></div>

<p><strong>financial_data</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20240102143158/Table_finance.png' style='border: solid black 5px'><br><small><i>Table: financial_data</i></small></div>

#### <strong><span style='color: #FFA07A'><strong>1. AVG() Function</strong></span></strong>

<p>Calculate the average or arithmetic mean for a group of numbers or a numeric column.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>AVG</span>(column_name) 
        <span style='color: #BD6B09'>FROM</span> table_name;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Example Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>AVG</span>(marks) 
        <span style='color: #BD6B09'>AS</span> average_marks 
        <span style='color: #BD6B09'>FROM</span> studentDetails;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20231224235150/AVG().png' style='border: solid black 5px'><br><small><i>AVG_MARKS</i></small></div>

#### <strong><span style='color: #FFA07A'><strong>2. SUM() Function</strong></span></strong>

<p>The total of all numeric values in a group i.e. Calculates the total sum of values in a numeric column.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>SUM</span>(column_name) 
        <span style='color: #BD6B09'>FROM</span> table_name;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Example Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>SUM</span>(marks) 
        <span style='color: #BD6B09'>AS</span> total_marks 
        <span style='color: #BD6B09'>FROM</span> studentDetails;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20231225001854/SUM().png' style='border: solid black 5px'><br><small><i>Sum of marks</i></small></div>


#### <strong><span style='color: #FFA07A'><strong>3. Count() Function</strong></span></strong>

<p>The number of cell locations in a range that contain a numeric character i.e Counts the number of rows in a result set or the number of non-null values in a column.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>COUNT</span>(*) 
        <span style='color: #BD6B09'>FROM</span> table_name;
      </strong>
    </td>
  </tr>
  <tr style='border: solid white'>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>COUNT</span>(column_name) 
        <span style='color: #BD6B09'>FROM</span> table_name;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Example Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>COUNT</span>(studentID) 
        <span style='color: #BD6B09'>AS</span> total_students 
        <span style='color: #BD6B09'>FROM</span> studentDetails;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20231225001957/COUNT().png' style='border: solid black 5px'><br><small><i>Count of Student</i></small></div>

<p><strong>Example Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>COUNT</span>(*) 
        <span style='color: #BD6B09'>FROM</span> studentdetails;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong></p>

<p>Return the count of rows that meet a specified condition .</p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20231231173513/countAll.png' style='border: solid black 5px'><br><small><i>count all rows</i></small></div>

#### <strong><span style='color: #FFA07A'><strong>4. Max() Function</strong></span></strong>

<p>Returns the highest numeric value in a group of numbers.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>MAX</span>(column_name) 
        <span style='color: #BD6B09'>FROM</span> table_name;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Example Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>MAX</span>(marks) 
        <span style='color: #BD6B09'>AS</span> highest_marks 
        <span style='color: #BD6B09'>FROM</span> studentDetails;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20231225002033/MAX().png' style='border: solid black 5px'><br><small><i>Maximum marks</i></small></div>

#### <strong><span style='color: #FFA07A'><strong>5. MIN() Function</strong></span></strong>

<p>Returns the lowest numeric value in a group of numbers.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>MIN</span>(column_name) 
        <span style='color: #BD6B09'>FROM</span> table_name;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Example Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>MIN</span>(marks) 
        <span style='color: #BD6B09'>AS</span> lowest_marks 
        <span style='color: #BD6B09'>FROM</span> studentDetails;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20231225002106/MIN().png' style='border: solid black 5px'><br><small><i>Minimum marks</i></small></div>

#### <strong><span style='color: #FFA07A'><strong>6. VAR() / VARIANCE() Function</strong></span></strong>

<p>Calculates the population variance of a numeric column.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>VAR</span>(column_name) 
        <span style='color: #BD6B09'>FROM</span> table_name;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Example Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>VARIANCE</span>(marks) 
        <span style='color: #BD6B09'>AS</span> variance_marks 
        <span style='color: #BD6B09'>FROM</span> studentDetails;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20231225002153/VAR().png' style='border: solid black 5px'><br><small><i>Variance marks</i></small></div>

#### <strong><span style='color: #FFA07A'><strong>7. STDDEV() / STDDEV_POP() Function</strong></span></strong>

<p>The standard deviation for a group of numbers based on a sample.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>STDDEV</span>(column_name) 
        <span style='color: #BD6B09'>FROM</span> table_name;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Example Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>STDDEV</span>(marks) 
        <span style='color: #BD6B09'>AS</span> stddev_marks 
        <span style='color: #BD6B09'>FROM</span> studentDetails;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20231225002236/STDDEV().png' style='border: solid black 5px'><br><small><i>Standrad deviation for marks</i></small></div>

#### <strong><span style='color: #FFA07A'><strong>8. PERCENTILE_CONT() Function</strong></span></strong>

<p>Calculates a specified percentile value for a numeric column.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>PERCENTILE_CONT</span>(<span style='color: #008000'>0.5</span>) 
        <span style='color: #BD6B09'>WITHIN GROUP</span> (<span style='color: #BD6B09'>ORDER BY</span> column_name) 
        <span style='color: #BD6B09'>FROM</span> table_name;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Example Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>PERCENTILE_CONT</span>(<span style='color: #008000'>0.5</span>) 
        <span style='color: #BD6B09'>WITHIN GROUP</span> (<span style='color: #BD6B09'>ORDER BY</span> salary) 
        <span style='color: #BD6B09'>AS</span> median_salary 
        <span style='color: #BD6B09'>FROM</span> employees;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20240102145725/percentail().png' style='border: solid black 5px'><br><small><i>Median salary of employee’s</i></small></div>

#### <strong><span style='color: #FFA07A'><strong>9. CORR() Function</strong></span></strong>

<p>Calculates the correlation coefficient between two numeric columns.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>CORR</span>(column1, column2) 
        <span style='color: #BD6B09'>FROM</span> table_name;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Example Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>CORR</span>(sales, profit) 
        <span style='color: #BD6B09'>AS</span> correlation_coefficient 
        <span style='color: #BD6B09'>FROM</span> sales_data;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20240102145849/Corr().png' style='border: solid black 5px'><br><small><i>correlation coefficient between ‘sales’ and ‘profit’</i></small></div>

#### <strong><span style='color: #FFA07A'><strong>10 .COVAR_POP() Function</strong></span></strong>

<p>Calculates the population covariance between two numeric columns.</p>

<p><strong>Syntax</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>COVAR_POP</span>(column1, column2) 
        <span style='color: #BD6B09'>FROM</span> table_name;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Example Query</strong></p>

<table align='center' style='border: solid white; padding-top: 20px; padding-bottom: 0px;'>
  <tr>
    <td style='background-color: #F0F0F0'>
      <strong>
        <span style='color: #BD6B09'>SELECT</span> <span style='color: #BD6B09'>COVAR_POP</span>(revenue, expenses) 
        <span style='color: #BD6B09'>AS</span> population_covariance 
        <span style='color: #BD6B09'>FROM</span> financial_data;
      </strong>
    </td>
  </tr>
</table>

<p><strong>Output</strong></p>

<div align='center'><img src='https://media.geeksforgeeks.org/wp-content/uploads/20240102145943/covarrPOP().png' style='border: solid black 5px'><br><small><i>Population Covariance between revenue and expenses</i></small></div>

## <span style='color: #BD6B09'><strong>Conclusion</strong></span>

<p>In SQL, <strong>statistical functions</strong> help to analyze and summarise data in the database. These functions assist in extracting meaningful information from the given datasets. For determining the number of occurrences , calculating totals , finding averages or calculating the variance in the dataset statistical functions plays a vital role .Overall, the integration of Statistical Functions elevates SQL’s capabilities, making it an invaluable asset for businesses and analysts seeking actionable intelligence from their relational databases.</p>